### ISSUE TITLE
Question about completeness of patch

### ISSUE THREAD

**Issue by wkjds** [oxygenxml/oxygen-log4j-patcher#11]
Hello,
I have Oxygen 20.1 installed on my Windows machine. After running the patch, I see updated Log4j 2.17.1 versions in the "Libraries" view.
However, when running scans for older Log4J versions, I am still seeing them popping up in the following directories:

C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\plugins\com.oxygenxml.common\lib\log4j-1.2.17.jar
C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\plugins\com.oxygenxml.pdf.css\lib\log4j-1.2.17.jar
C:\Program Files\Oxygen XML Editor 20\frameworks\docbook\xsl\com.oxygenxml.webhelp.classic\lib\log4j-1.2.17.jar
C:\Program Files\Oxygen XML Editor 20\lib\log4j.jar

Is the patch meant to update the versions of log4j in these directories? If not, is there another mitigation for updating them?

I appreciate any guidance anyone can provide.

**Comment by raducoravu** [comment]
Hi, 

Oxygen versions older than 22.1 (meaning 22.0 and older) use the Apache 1.x log4j instead of the 2.x log4j.
Apache 1.x log4j has a totally different internal architecture and it also did not have the feature that caused this problem in the 2.x log4j. So the patcher just patches the Apache 2.x log4j which has this particular security problem.
